server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/book_service
    user: postgres
    password: postgres
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
management:
  tracing:
    sampling:
      probability: 1.0
