name: Continuous Integration with Github

on: [push]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      naming-server: /home/runner/work/microservices-course/microservices-course/naming-server

    steps:
      - name: Login into Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Ensure permissions for microservices-course
        run: |
          chmod -R a+rX /home/runner/work/microservices-course/microservices-course/

      - name: List contents of /home/runner/work/microservices-course/microservices-course
        run: ls -al /home/runner/work/microservices-course/microservices-course